sudo: false
language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm cache clean --force
  - npm i -g npm@6
  - npm install
script:
  - npm run ci
after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test1;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test2;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test3;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test4;'
